### PR TITLE
chore: update to version 5.5.0

### PR DESCRIPTION
**Pull request by sitic**

### CODE REVIEW

**Comment by paddy-hack** [comment]
BTW, I'd also appreciate it if the images on the Docker Hub were versioned :bow:

**Comment by jberrenberg** [comment]
@sitic thanks for the MR

@paddy-hack i will try =)

**Comment by paddy-hack** [comment]
Forgot to mention 5.5.1 was released :cry:

**Comment by paddy-hack** [comment]
Thanks for pushing a 5.5.1 tagged image! :bow:

**Pull request merged**
